# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
    hooks:
        - go mod tidy

builds:
    - id: tag-it-cli
      main: ./cmd/cli
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
    - id: tag-it-ci
      main: ./cmd/ci
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin

upx:
    - enabled: true
      compress: "7"

gitea_urls:
    download: https://gitea.retzer.xyz
    api: https://gitea.retzer.xyz/api/v1

archives:
    - id: ci
      format: tar.gz
      builds:
          - tag-it-ci
      name_template: >-
          {{ .ProjectName }}-CI_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
          {{- if .Arm }}v{{ .Arm }}{{ end }}
      format_overrides:
          - goos: windows
            format: zip
    - id: cli
      format: tar.gz
      builds:
          - tag-it-cli
      name_template: >-
          {{ .ProjectName }}-CLI_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
          {{- if .Arm }}v{{ .Arm }}{{ end }}
      format_overrides:
          - goos: windows
            format: zip

aurs:
    - homepage: "https://gitea.retzer.xyz/pyscripter99/tag-it"
      description: Tag-It is a CI and CLI tool to bump semver versions
      maintainers:
        - "pyscripter99 <ryder@retzlaff.family>"
      license: AGPL-3.0
      private_key: '{{ .Env.AUR_KEY }}'
      git_url: 'ssh://aur@aur.archlinux.org/tag-it-bin.git'
      

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
