version: 1

when:
    - event: [pull_request, tag]
    - event: push

variables:
    - &golang_image "docker.io/golang:1.22.1"

steps:
    vendor:
        image: *golang_image
        group: prepare
        commands:
            - go mod vendor

    test_ci:
        image: *golang_image
        group: test
        commands:
            - go build ./cmd/ci
            - go build ./cmd/cli
            - go test ./test -v
