when:
    event: tag

clone:
    git:
        image: woodpeckerci/plugin-git

pipeline:
    release:
        image: goreleaser/goreleaser
        commands:
            - ko login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - goreleaser release
        secrets: [gitea_token, docker_username, docker_password]
        when:
            event: tag
