when:
    event: tag

clone:
    git:
        image: woodpeckerci/plugin-git

pipeline:
    release:
        image: goreleaser/goreleaser
        commands:
            - wget https://github.com/ko-build/ko/releases/download/v0.15.0/ko_0.15.0_Linux_arm64.tar.gz
            - tar -xzf ko_0.15.0_Linux_arm64.tar.gz ko
            - chmod +x ./ko
            - ./ko login registry-1.docker.io -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            - rm ko ko_0.15.0_Linux_arm64.tar.gz
            - goreleaser release
        secrets: [gitea_token, docker_username, docker_password]
        when:
            event: tag
